# Default image for Linux builds
image: objectboxio/buildenv-android:2023-08-29

variables:
  # Disable the Gradle daemon. Gradle may run in a Docker container with a shared
  # Docker volume containing GRADLE_USER_HOME. If the container is stopped after a job
  # Gradle daemons may get killed, preventing proper clean-up of lock files in GRADLE_USER_HOME.
  # Use low priority processes to avoid Gradle builds consuming all build machine resources.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.priority=low"

stages:
  - build

build:
  stage: build
  tags: [ docker, x64 ]
  script:
    
    - echo "➡️ Building client-java..."
    - cd tasks/client-java
    - ./gradlew clean build
    - echo "✅ Building client-java...DONE"
    - cd ../..

    - echo "➡️ Building client-android-java..."
    - cd tasks/client-android-java
    - ./gradlew clean build
    - echo "✅ Building client-android-java...DONE"
    - cd ../..

    - echo "➡️ Building client-android-kotlin..."
    - cd tasks/client-android-kotlin
    - ./gradlew clean build
    - echo "✅ Building client-android-kotlin...DONE"
    - cd ../..

  artifacts:
    when: always
    paths:
      - "**/build/reports/lint-results-debug.html"
