variables:
  # Disable the Gradle daemon. Gradle may run in a Docker container with a shared
  # Docker volume containing GRADLE_USER_HOME. If the container is stopped after a job
  # Gradle daemons may get killed, preventing proper clean-up of lock files in GRADLE_USER_HOME.
  # Use low priority processes to avoid Gradle builds consuming all build machine resources.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.priority=low"
  # Maven arguments
  # --batch-mode: recommended in CI, run in non-interactive mode (disables output color)
  # --show-version: strongly recommended in CI, will display the JDK and Maven versions in use.
  #      Very useful to be quickly sure the selected versions were the ones you think.
  # --errors: Produce execution error messages, useful for plugin developers (like us).
  MVN_ARGS: "--batch-mode --show-version --errors"

stages:
  - build

java-sdk-examples:
  stage: build
  tags: [ docker, linux, x64 ]
  image: objectboxio/buildenv-android:2024-12-09
  script:
    
    - cd tasks/client-java
    - echo "➡️ Building client-java with Gradle..."
    - ./gradlew clean build
    - echo "✅ Building client-java with Gradle...DONE"
    - echo "➡️ Building client-java with Maven..."
    - ./mvnw $MVN_ARGS compile
    - echo "✅ Building client-java with Maven...DONE"
    - cd ../..

    - echo "➡️ Building client-android-java..."
    - cd tasks/client-android-java
    - ./gradlew clean build
    - echo "✅ Building client-android-java...DONE"
    - cd ../..

    - echo "➡️ Building client-android-kotlin..."
    - cd tasks/client-android-kotlin
    - ./gradlew clean build
    - echo "✅ Building client-android-kotlin...DONE"
    - cd ../..

  artifacts:
    when: always
    paths:
      - "**/build/reports/lint-results-debug.html"

swift-sdk-examples:
  stage: build
  tags: [mac, x64, xcode]
  script:
    - cd tasks/client-swift
    # A simulator named "iPhone 11" is configured on the build machine
    - xcodebuild clean build -scheme client-swift-ios -destination 'platform=iOS Simulator,name=iPhone 11'
    - xcodebuild build -scheme client-swift-macos -destination 'platform=macOS'
