services:
  sync-server:
    image: objectboxio/sync-server-trial:latest
    platform: linux/amd64
    container_name: sync-server
    restart: always
    # Note: user and group ID 1000 may have to be adjusted to match your user IDs:
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "9980:9980"
      - "9999:9999"
    volumes:
      # Expose "current" (this) directory as "/data" in the container.
      - .:/data
      - ./sync-server-config.json:/data/sync-server-config.json:ro
    command: >
      --conf ./sync-server-config.json
      --model ./objectbox-model.json    
      --admin-bind 0.0.0.0:9980 
      --mongo-url ${MONGO_URL}
      --mongo-db ${MONGO_DB}
      --debug

      
    

