version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db # Keep data across restarts; volume worked better than directory due to permission issues
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  # Instead of healthcheck "spamming" the log, have a "waiter" container here.
  # It's sole purpose is to sleep a few seconds to give MongoDB time to boot up before starting the Sync Server.
  mongo-waiter:
    image: objectboxio/sync-server-trial # Use the same image as we already have it
    container_name: mongo-waiter
    entrypoint: ["/bin/sleep", "5"] # Wait for 5 seconds; adjust as needed
    depends_on:
      - mongo

  sync-server:
    image: objectboxio/sync-server-trial
    container_name: sync-server
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    network_mode: "host"  # Docker network name resolution caused connection issues
    volumes:
      - .:/data
    command: >
      --model /data/objectbox-model.json
      --unsecured-no-authentication 
      --admin-bind 0.0.0.0:9980 
      --mongo-url mongodb://localhost:27017/?replicaSet=rs0
      --mongo-db test-db
    depends_on:
      mongo-waiter:
        condition: service_completed_successfully

volumes:
  mongo-data: