version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db # Keep data across restarts; volume worked better than directory due to permission issues

  mongo-init: # Run init script to initialize replica set
    image: mongo:8
    depends_on:
      mongo:
        condition: service_started
    entrypoint: ["bash","/mongo-init.sh"]
    volumes:
      - ./mongo-init.sh:/mongo-init.sh:ro
    restart: 'no'

  sync-server:
    image: objectboxio/sync-server-trial
    container_name: sync-server
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "9980:9980"
      - "9999:9999"
    volumes:
      - .:/data
    command: >
      --model /data/objectbox-model.json
      --unsecured-no-authentication 
      --admin-bind 0.0.0.0:9980 
      --mongo-url mongodb://mongo:27017/?replicaSet=rs0
      --mongo-db test-db
    #  --debug
    depends_on:
      mongo-init:
        condition: service_completed_successfully

volumes:
  mongo-data: